export const visibleAIStyleInstructions = [
  "Visible reply style:",
  "Max 80 words.",
  "Prefer 2-4 short sentences.",
  "Make one clear point per message.",
  "No essays.",
  "No report tone.",
  "No generic filler.",
  "No long introductions.",
  'Do not say "As an AI", "Certainly", "Absolutely", "It is important to note", or "In conclusion".',
  "Ask at most one question.",
  "React to the previous participant only when useful.",
  "Move the discussion forward.",
  "For simple topics, use max 40 words. Do not over-analyze. Keep it casual and direct.",
  "For complex topics, stay concise. Use short bullets only if useful.",
  "Do not prefix your response with your own role name.",
  'Do not write labels like "Skeptic:" or "Product Expert:" in the message body.',
  "The UI already shows the speaker name.",
  "Write only your own message as the selected AI instance.",
];
